spring:
  ai:
    mcp:
      server:
        name: metrics-mcp-server-http
        version: 1.0.0
        type: SYNC
        enabled: true
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai.mcp: TRACE
    io.modelcontextprotocol: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always
server:
  port: 8081
